### ISSUE TITLE
GDB performs step instead of next

### ISSUE THREAD

**Issue by Sermus** [espressif/esp-gdbstub#5]
There is a code like this:
8:  void user_init()
9:   {
10:    f2();
11: }

both are located in flash.

Scenario:
1) hbr user_init
2) c
It stops at the beginnign of user_init, line 9
3) next
It shows 
10 f2()
4) next
Expectation is that it goes to line 11
Actual result is that it goes into f2 and produces the message like this:
Warning:
Cannot insert breakpoint 0.
Error accessing memory address 0x4028f3ab: Input/output error.

**Comment by Spritetm** [comment]
Unfortunately, that's a hardware limitation combined with the way gdb handles single-stepping. With step 1, you already use the single available hardware breakpoint, forcing gdb to use software breakpoints from then on. With step 4, you implicitely ask gdb to set a breakpoint on the next line and run to there. Gdb tries to put a software breakpoint to do this, but because the routine is in flash, gdbstub is unable to and fails with the given message.

**Comment by Sermus** [comment]
Hm, should it do it a proper way if i remove hbr between steps 1 and 2? I tried and the behavior is still the same, it does stepping into instead of stepping next line.

**Comment by Spritetm** [comment]
It should, but I don't know how gdb react if it can't place a software breakpoint on a certain location. Theoretically, gdbstub could intercept that and use a hardware breakpoint itself, but that's a pretty non-trivial thing to implement.
